
-----CREATE A TABLE-----

CREATE TABLE ELECTRONICS_SALES(
ORDERID INT PRIMARY KEY,
ORDERDATE DATE,
CUSTOMER VARCHAR(20),
CITY VARCHAR(20),
PRODUCT VARCHAR(20),
CATEGORY VARCHAR(20),
QUANTITY INT,
UNITPRICE INT,
PAYMENTMETHOD VARCHAR(20)
);

----INSERT THE VALUES INTO THE TABLE-----

INSERT INTO ELECTRONICS_SALES VALUES
(4001,'2026-02-20','RAHUL','DELHI','LAPTOP','COMPUTERS',1,65000,'CARD'),
(4002,'2026-02-20','NEHA','MUMBAI','SMARTPHONE','MOBILE',2,30000,'UPI'),
(4003,'2026-02-21','AMIT','BANGALORE','HEADPHONES','ACCESSORIES',3,2000,'CASH'),
(4004,'2026-02-21','PRIYA','DELHI','TABLET','MOBILE',1,25000,'CARD'),
(4005,'2026-02-22','KARAN','HYDERABAD','LAPTOP','COMPUTERS',1,70000,'UPI'),
(4006,'2026-02-22','NEHA','MUMBAI','SMARTWATCH','ACCESSORIES',2,8000,'CARD'),
(4007,'2026-02-23','RAHUL','BANGALORE','SMARTPHONE','MOBILE',1,32000,'UPI'),
(4008,'2026-02-23','PRIYA','HYDERABAD','HEADPHONES','ACCESSORIES',2,2200,'CASH'),
(4009,'2026-02-24','AMIT','DELHI','LAPTOP','COMPUTERS',1,68000,'CARD'),
(4010,'2026-02-24','KARAN','MUMBAI','TABLET','MOBILE',1,2000,'UPI')

----SEE THE WHOLE DATA-----

SELECT * FROM ELECTRONICS_SALES;

----TOTAL REVENUE----

SELECT 
  SUM(QUANTITY*UNITPRICE) AS TOTALREVENUE
FROM ELECTRONICS_SALES;

------REVENUE BY PRODUCT-----

SELECT 
  PRODUCT,
  SUM(QUANTITY*UNITPRICE) AS TOTALREVENUE
FROM ELECTRONICS_SALES
GROUP BY PRODUCT
ORDER BY TOTALREVENUE DESC;

-----REVENUE BY CITY------

SELECT 
  CITY,
  SUM(QUANTITY*UNITPRICE) AS TOTALREVENUE
FROM ELECTRONICS_SALES
GROUP BY CITY
ORDER BY TOTALREVENUE DESC;

-----REVENUE BY CATEGORY-----

SELECT 
  CATEGORY,
  SUM(QUANTITY*UNITPRICE) AS TOTALREVENUE
FROM ELECTRONICS_SALES
GROUP BY CATEGORY
ORDER BY TOTALREVENUE DESC;

-----REVENUE BY DATE-----

SELECT 
  ORDERDATE,
  SUM(QUANTITY*UNITPRICE) AS TOTALREVENUE
FROM ELECTRONICS_SALES
GROUP BY ORDERDATE
ORDER BY TOTALREVENUE DESC;
